# .github/workflows/deploy.yml

name: deploy
on:
  push:
    branches:
      # Déclenchement de notre workflow lors d'un push sur la branche `main`
      - main
    paths-ignore:
      - "bin/**"
      - "README.md"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Récupération de notre dépôt sous `${GITHUB_WORKSPACE}`,
        # pour que notre workflow puisse y accéder
        uses: actions/checkout@v4.1.1
        with:
          # Récupère l'intégralité de l'historique Git
          fetch-depth: 0

      # - name: Deploy via SFTP
      #   # Utilisation de l'action 'marvinpinto/ftp-deploy-action' pour déployer via SFTP
      #   uses: marvinpinto/ftp-deploy-action@v3
      #   with:
      #     # Détails de connexion SFTP et identifiants d'utilisateur SFTP dans le contexte secret
      #     server: ${{ secrets.SFTP_HOST }}
      #     username: ${{ secrets.SFTP_USER }}
      #     password: ${{ secrets.SFTP_PASS }}
      #     # Port SFTP
      #     port: ${{ secrets.SFTP_PORT }}
      #     # Chemin vers le répertoire de votre thème
      #     local-dir: "./wp-content/themes/my-theme"
      #     # Répertoire distant où déployer le thème
      #     remote-dir: "/wp-content/themes/my-theme"
      #     # Options supplémentaires pour le déploiement
      #     args: "--verbose"
